### ISSUE TITLE
Dealer is unable to add assistant

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#169] opened 2017-10-20 22:59 UTC
`Traceback (most recent call last): File "/app/plugins/uber/uber/decorators.py", line 187, in charge return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken) File "/app/plugins/uber/uber/site_sections/preregistration.py", line 421, in pay_for_extra_members session.assign_badges(group, group.badges + badges_to_add) File "/app/plugins/uber/uber/models.py", line 1070, in badges return len(self.attendees) File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__ return self.impl.get(instance_state(instance), dict_) File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get value = self.callable_(state, passive) File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state (orm_util.state_str(state), self.key) sqlalchemy.orm.exc.DetachedInstanceError: Parent instance is not bound to a Session; lazy load operation of attribute 'attendees' cannot proceed
 `

Dealer reported that they were attempting to add a dealer assistant and pay for it.

From the dealer:

> > I pressed the button "click here to add more Dealer Assistants"
> It then gave me a drop down for number next to the button "Add Dealer Assistants"
> I then chose to pay with card, entered my credit card information, and pressed the button to pay $55.
> 
> That was when I got a new screen with that block of text.
>

**Comment by jmdawson** [comment] 2017-10-20 23:20
From RAMS
`Got an error while calling charge(self, payment_id='PAYMENT_ID', stripeToken='TOKEN', ignored={'stripeTokenType': 'card'}):
Traceback (most recent call last):
 File "/app/plugins/uber/uber/decorators.py", line 187, in charge
   return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken)
 File "/app/plugins/uber/uber/site_sections/preregistration.py", line 421, in pay_for_extra_members
   session.assign_badges(group, group.badges + badges_to_add)
 File "/app/plugins/uber/uber/models.py", line 1070, in badges
   return len(self.attendees)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
   return self.impl.get(instance_state(instance), dict_)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
   value = self.callable_(state, passive)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
   (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Group at 0x7f7cca4d4d68> is not bound to a Session; lazy load operation of attribute 'attendees' cannot proceed


IMPORTANT: This could have resulted in an attendee paying and not beingmarked as paid in the database. Definitely double check.
Traceback (most recent call last):
 File "/app/plugins/uber/uber/decorators.py", line 187, in charge
   return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken)
 File "/app/plugins/uber/uber/site_sections/preregistration.py", line 421, in pay_for_extra_members
   session.assign_badges(group, group.badges + badges_to_add)
 File "/app/plugins/uber/uber/models.py", line 1070, in badges
   return len(self.attendees)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
   return self.impl.get(instance_state(instance), dict_)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
   value = self.callable_(state, passive)
 File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
   (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Group at 0x7f7cca4d4d68> is not bound to a Session; lazy load operation of attribute 'attendees' cannot proceed`

**Comment by kitsuta** [comment] 2017-10-21 14:47
This error is reproducible, which is really helpful.

For that dealer, a good workaround (if not done so already) would be having an admin add group members to the group.

**Comment by ianlayton** [comment] 2017-10-21 15:04
Yeah, I got this one instance fixed since the payment went through correctly. I manually added a membership to the group and adjusted the payment for the missed payment.

**Comment by kitsuta** [comment] 2017-10-21 20:37
Fixed by https://github.com/MidwestFurryFandom/rams/pull/171!

**Closed** 2017-11-14 05:55 UTC
