### ISSUE TITLE
Badge Name field is not displayed

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#68] opened 2017-04-24 15:55 UTC
Set the following, but do not see badge name field on reg page.
`printed_badge_deadline = "2018-11-14"`

**Comment by kitsuta** [comment] 2017-04-26 02:32
Whoops, duplicate of https://github.com/MidwestFurryFandom/rams/issues/80.

**Closed by kitsuta** 2017-04-26 02:32 UTC
