### ISSUE TITLE
Reassigned badge numbers

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#224] opened 2017-12-07 20:21 UTC
Not sure if a gotcha or an issue. 

When upgrading from one level to another, it appears that the system will sometimes reassign the badge number of a person and make the previously used number available again. It doesn't seem to happen all the time though and I'm not sure if it's something that the operator is doing that's causing it.

Example badge 6990

**Comment by jmdawson** [comment] 2017-12-07 20:24
Shouldn't be...
```
[badge_ranges]
staff_badge = 1, 999
sponsor_badge = 1000, 39999
shiny_badge = 1000, 39999
guest_badge = 1000, 39999
attendee_badge = 1000, 39999
one_day_badge = 10000, 39999
```

**Comment by DavidWnek** [comment] 2018-12-04 18:09
I can confirm this happens. I upgraded my staff badge to shiny onsite, and went from 0242 to 56XX.

Caused a slight issue in Art Show because my badge name didn't match my physical badge.

**Comment by jmdawson** [comment] 2018-12-04 18:56
My first suspicion of what's happening here is that because all staff were of type "Attendee" but their numbers were set in the range for type "Staff", they were set to the next available number in the range appropriate to their badge (Attendee & sponsor types share the same range) when they were saved.

**Comment by kitsuta** [comment] 2018-12-04 22:00
Yeah, the system does enforce badge type ranges. Technically the bug is
that it let you set numbers outside the range in the first place, but if
that was done via the CSV upload I'm not surprised.

**Comment by jmdawson** [comment] 2018-12-04 22:20
Fixed badge numbers for staff are something the board wants, so we're going to have to do something about this. One of those might be to figure out how to handle the fact that staff can be sponsors & super sponsors.

**Comment by jmdawson** [comment] 2018-12-05 16:56
Continuing to think out loud, this sounds like the data model we want is not the same as what MAG wants and that's probably fairly problematic. On the other hand, maybe MAG is willing to entertain a revised, more flexible data model?

**Comment by jmdawson** [comment] 2021-10-08 15:14
Question marks here, @fusuit69 please take a gander

**Comment by kitsuta** [comment] 2022-09-13 12:11
We've fixed a lot of issues around this, but there's one remaining -- the admin form automatically checks the "Use next available badge #" when you change the badge type:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/7198215/189897559-0164e48b-4727-47e1-8fa1-35ca1fb53597.png">

Once that's fixed, we should be able to close this (finally).

**Closed** 2023-06-20 01:59 UTC
Labels: 2019, before launch, needs more information, 2021
